[package]
name = "ci-workflow"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ci-core = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
